$primary_paletteKeyColor = 28828d
$secondary_paletteKeyColor = 627b7f
$tertiary_paletteKeyColor = 6a7798
$neutral_paletteKeyColor = 727879
$neutral_variant_paletteKeyColor = 6f797a
$background = 0e1415
$onBackground = dee4e4
$surface = 0e1415
$surfaceDim = 0e1415
$surfaceBright = 343a3b
$surfaceContainerLowest = 090f10
$surfaceContainerLow = 171d1e
$surfaceContainer = 1b2122
$surfaceContainerHigh = 252b2c
$surfaceContainerHighest = 303637
$onSurface = dee4e4
$surfaceVariant = 3f484a
$onSurfaceVariant = bec8ca
$inverseSurface = dee4e4
$inverseOnSurface = 2b3132
$outline = 899294
$outlineVariant = 3f484a
$shadow = 000000
$scrim = 000000
$surfaceTint = 81d3df
$primary = 81d3df
$onPrimary = 00363c
$primaryContainer = 004f57
$onPrimaryContainer = 9df0fc
$inversePrimary = 006973
$secondary = b1cbcf
$onSecondary = 1c3438
$secondaryContainer = 324b4e
$onSecondaryContainer = cde7eb
$tertiary = b9c6ea
$onTertiary = 23304d
$tertiaryContainer = 8490b2
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = 9df0fc
$primaryFixedDim = 81d3df
$onPrimaryFixed = 001f23
$onPrimaryFixedVariant = 004f57
$secondaryFixed = cde7eb
$secondaryFixedDim = b1cbcf
$onSecondaryFixed = 051f22
$onSecondaryFixedVariant = 324b4e
$tertiaryFixed = d9e2ff
$tertiaryFixedDim = b9c6ea
$onTertiaryFixed = 0d1b37
$onTertiaryFixedVariant = 3a4664
$term0 = 343434
$term1 = 8383ff
$term2 = 45e1d4
$term3 = 75fcdd
$term4 = 76b4bc
$term5 = 7aaee9
$term6 = 80d8d7
$term7 = ccdcd6
$term8 = 9aa59f
$term9 = a29eff
$term10 = 17f7e8
$term11 = c9fff3
$term12 = a3c7c9
$term13 = a2c0f7
$term14 = 87ece9
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 6bccf4
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d1faf1
$green = 8af1ef
$teal = 9fedf3
$sky = 94e8f5
$sapphire = 74d5e8
$blue = 5ecae7
$lavender = 8bd7f2
$klink = 0094ac
$klinkSelection = 0094ab
$kvisited = 008bb5
$kvisitedSelection = 008bb5
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bcbe
$kpositiveSelection = 00bcbd
$text = dee4e4
$subtext1 = bec8ca
$subtext0 = 899294
$overlay2 = 777f81
$overlay1 = 646c6e
$overlay0 = 535a5c
$surface2 = 42494b
$surface1 = 32383a
$surface0 = 202627
$base = 0e1415
$mantle = 0e1415
$crust = 0d1314
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
