#!/bin/bash

if [[ -z "$1" ]]; then
    echo "Usage: webapp-install <APP_NAME> <APP_URL>"
    echo ""
    echo "Example: webapp-install Whatsapp https://web.whatsapp.com"
    exit 1
fi

APP_NAME="$1"
APP_URL="$2"

if [[ -z "$APP_NAME" || -z $APP_URL ]]; then
    echo "What? you want me to create ghost webapp?.. give me the webapp you want to make.. bad bunny."
    exit 1
fi

BROWSER="brave"

if ! command -v brave &> /dev/null; then
    echo "failed to get $BROWSER. are you sure it's installed?"
    exit 1
fi

if [[ $# -lt 3 ]]; then
    FAVICON_URL="https://www.google.com/s2/favicons?domain=${APP_URL}&sz=128"
else
    FAVICON_URL="$3"
fi

ICON_DIR="$HOME/.local/share/applications/webapps-icon"
mkdir -p "$ICON_DIR"
ICON_PATH="$ICON_DIR/$APP_NAME.png"

echo "Installing $APP_URL's favicon..."

if ! curl -fsSL -o "$ICON_PATH" "$FAVICON_URL" || [[ ! -s "$ICON_PATH" ]]; then
    echo "BEEP! favicon download failed... guess the website doesn't like you."
    exit 1
fi

read -p "Do you wanna add custom description? [y/n] " confirm_desc

case $confirm_desc in
    [yY][eE][sS]|[yY]) ;;
    *) 
        echo "cancelled. Bye bye!~ 🐰"
        exit 1
        ;;
esac

read -p "Input your app desc: " APP_DESC

EXEC_COMMAND="$BROWSER --app=$APP_URL"

SAFE_NAME=$(echo "$APP_NAME" | tr ' ' '-') # "osu! lazer" -> "osu!-lazer"
DESKTOP_FILE="$HOME/.local/share/applications/$APP_NAME.desktop"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=$APP_NAME
Comment=$APP_DESC
Icon=$ICON_PATH
Exec=$EXEC_COMMAND
Terminal=false
StartupNotify=true
EOF

chmod +x "$DESKTOP_FILE"
update-desktop-database ~/.local/share/applications

echo "All done!~ $APP_NAME can be launched directly from your launcher!"
