#!/bin/bash

if [[ -z "$1" || -z "$2" ]]; then
    echo "Usage: webapp-install <APP_NAME> <APP_URL>"
    echo ""
    echo "Example: webapp-install Whatsapp https://web.whatsapp.com"
    exit 1
fi

BROWSER="brave"

ICON_DIR="$HOME/.local/share/applications/webapps-icon"
PROFILE_DIR="$HOME/.local/share/webapps"
DESKTOP_DIR="$HOME/.local/share/applications"

APP_NAME=$(echo "$1" | tr '[:upper:]' '[:lower:]')
APP_URL=$(echo "$2" | tr '[:upper:]' '[:lower:]')
SAFE_NAME=$(echo "$APP_NAME" | tr ' ' '-')
TITLE_NAME=$(echo "${APP_NAME^}")

ICON_PATH="$ICON_DIR/$SAFE_NAME.png"
PROFILE_PATH="$PROFILE_DIR/$SAFE_NAME"
DESKTOP_FILE="$DESKTOP_DIR/$SAFE_NAME.desktop"


error() {
    echo "BEEP! Error occurred!~~ $1"
    exit 1
}

command -v $BROWSER &> /dev/null || error "failed to get $BROWSER. Are you sure it's installed?"


FAVICON_URL="${3:-https://www.google.com/s2/favicons?domain=${APP_URL}&sz=128}"
echo "Installing $APP_URL's favicon..."
mkdir -p "$ICON_DIR"

curl -fsSL -o "$ICON_PATH" "$FAVICON_URL" || error "favicon download failed... guess the website doesn't like you."


read -p "Do you wanna add custom description? [y/n] " confirm_desc

case $confirm_desc in
    [yY][eE][sS]|[yY]) 
        read -p "Input your app desc: " APP_DESC
        ;;
    *) 
        APP_DESC="A fluffy shortcut to the web~ 🐰"
        ;;
esac


EXEC_COMMAND="$BROWSER \
--app="$APP_URL" \
--user-data-dir="$PROFILE_PATH" \
--no-first-run"

cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=$TITLE_NAME
Comment=$APP_DESC
Icon=$ICON_PATH
Exec=$EXEC_COMMAND
Terminal=false
StartupNotify=true
EOF

chmod +x "$DESKTOP_FILE"
update-desktop-database $HOME/.local/share/applications

echo "All done!~ $TITLE_NAME can be launched directly from your launcher!"
